FROM ansible/awx_web:{{ awx_web_tag }}
USER root
ADD launch_awx.sh /usr/bin/launch_awx.sh
ADD launch_awx_task.sh /usr/bin/launch_awx_task.sh
ADD settings.py /etc/tower/settings.py
COPY nginx.conf /etc/nginx/nginx.conf
RUN chmod +rx /usr/bin/launch_awx.sh && \
    chmod +rx /usr/bin/launch_awx_task.sh
USER 1000